Engage 3925 tableave
stroeer/stroeer-videoplayer-ima-plugin pull request #21
Opened 2022-12-08 15:31 UTC by ennoStroeer

The tab-leave feature (video pauses when the user switches to another tab in browser) has been moved from the videoplayer to the IVAD - and IMA - plugin, since it is mainly an ad demand.

Therefore the packages (stroeer-videoplayer, stroeer-videoplayer-ivad-plugin, stroeer-videoplayer-ima-plugin) must be updated simultaneously, when this behaviour should occur.

https://github.com/stroeer/video/issues/12
https://t-online.atlassian.net/browse/ENGAGE-3925The tab-leave feature (video pauses when the user switches to another tab in browser) has been moved from the videoplayer to the IVAD - and IMA - plugin, since it is mainly an ad demand.

Therefore the packages (stroeer-videoplayer, stroeer-videoplayer-ivad-plugin, stroeer-videoplayer-ima-plugin) must be updated simultaneously, when this behaviour should occur.

https://github.com/stroeer/video/issues/12
https://t-online.atlassian.net/browse/ENGAGE-3925

2022-12-12 10:44 UTC, walialu commented on src/plugin.test.ts
> +  getDataStore=(): any => {}
Wofuer brauchst du das hier? Sehe keinen Aufruf davon :thinking:

2022-12-12 10:44 UTC, walialu commented on src/plugin.ts
> +    //
Wozu die extra auskommentierte Zeile?

2022-12-12 10:44 UTC, walialu commented on types/types.d.ts
> +  getDataStore: Function
Wozu wird das gebraucht?

2022-12-12 10:44 UTC, walialu commented
Hier gibts  auch noch Conficts und es muss die Version in `package.json` hochgezaehlt werden.

2022-12-12 11:51 UTC, evaschmuhl requested changes

2022-12-12 11:51 UTC, evaschmuhl commented on src/plugin.ts
> +    const onVisibilityChangeCallback = (): void => {
Ich fänd es besser, wenn diese Funktion einheitlich wie zum Rest des Codes auch aus der Init ausgelagert wäre.

2022-12-12 15:50 UTC, ennoStroeer commented on src/plugin.ts
> +    //
für nix... ist raus

2022-12-12 15:50 UTC, ennoStroeer commented on types/types.d.ts
> +  getDataStore: Function
für nix... ist raus

2022-12-12 15:51 UTC, ennoStroeer commented on src/plugin.ts
> +    const onVisibilityChangeCallback = (): void => {
sollte jetzt ausgelagert sein, allerdings hab ich den Listener mit der Abhängigkeit vom data Attribut drin gelassen

2022-12-14 07:00 UTC, evaschmuhl approved these changes
Danke fürs Anpassen!

2022-12-14 09:43 UTC, merged